import DOMPurify, { type Config as DomPurifyConfig } from "dompurify";

const DISCUSSION_HTML_SANITIZE: DomPurifyConfig = {
  ADD_TAGS: [
    "img",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "table",
    "thead",
    "tbody",
    "tfoot",
    "tr",
    "th",
    "td",
    "colgroup",
    "col",
    "figure",
    "figcaption",
    "blockquote",
    "hr",
    "br",
    "span",
    "div",
    "u",
    "s",
    "sub",
    "sup",
    "ul",
    "ol",
    "li",
    "p",
    "strong",
    "em",
    "a",
  ],
  ADD_ATTR: [
    "src",
    "alt",
    "title",
    "href",
    "target",
    "rel",
    "colspan",
    "rowspan",
    "class",
    "style",
    "width",
    "height",
    "data-align",
  ],
};

export function sanitizeDiscussionHtml(html: string) {
  return DOMPurify.sanitize(html || "", DISCUSSION_HTML_SANITIZE);
}
